services:
  lazypay:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lazypay
    restart: unless-stopped
    ports:
      - "127.0.0.1:8940:8940"
    volumes:
      - ./data:/app/data
      - ./downloads:/app/downloads
      - ./server/.env:/app/server/.env
    env_file:
      - .env
